# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.15"
    displayName: "Install Node.js"
  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: "javascript"
      querysuite: "security-extended"

  - script: |
      npm install -g @angular/cli
      npm install -f
      npm audit fix
      npm run build --output-path=dist/rst/browser
    displayName: "npm install and build"

  - task: AdvancedSecurity-Dependency-Scanning@1
  - task: AdvancedSecurity-Codeql-Analyze@1

  - task: AzureStaticWebApp@0
    inputs:
      app_build_command: "npm run build"
      app_location: "dist/rst/browser/"
      output_location: "dist/out-tsc"
      skip_app_build: true
      skip_api_build: true
      azure_static_web_apps_api_token: "$(token)"
    env:
      NG_APP_RECAPTCHA: "6LfPTd8mAAAAAI8JTLzFdG0jOUfWe12EkX67xcAt"
